WITH result AS (SELECT
CreatedDate as date,
EXTRACT (WEEK from CreatedDate) as week,
EXTRACT (MONTH from CreatedDate) as month,
Id as leads_id,
GACLIENTID__c as GA_Id,
Name,
Email as email,
Mktg_Campaign__c as mktg_campaign,
LOWER (COALESCE(Mktg_Medium__c,'Unknown')) as mktg_medium,
LOWER (COALESCE(Mktg_Source__c,'Unknown')) as mktg_source,
LOWER (COALESCE(LeadSource,'Unkown')) as lead_source,
COALESCE (Mktg_Landing_Page__c,'Unkown') as landing_page,
COALESCE (status, 'Unknown') as lead_status,
COALESCE (Business_Unit_Owner__c, 'Unknown') as business_unit,
LOWER (COALESCE(Industry, 'Unknown')) as industry,
Site_Address_Postcode__c as postcode,
COALESCE (NZ_Site_Address_State__c, 'Unknown') as state,
LOWER (COALESCE(Closed_Status_Reason__c, 'Unkown')) as closed_status_reason,
Age_Days__c as lead_age,
COUNT (*) as total_leads,
ROW_NUMBER() OVER (
  PARTITION BY DATE (CreatedDate), Email, Site_Address_Postcode__c
  ORDER BY CreatedDate DESC
) AS row_num,
FROM salesforce.data
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
ORDER BY 1 DESC)

SELECT
result.date,
result.week,
result.month,
result.leads_id,
COALESCE(result.GA_Id,'Unknown') as GA_Id,
result.Name,
result.email,
result.mktg_campaign,
result.mktg_medium,
result.mktg_source,
result.lead_source,
result.category,
result.landing_page,
result.lead_status,
result.business_unit,
result.industry,
COALESCE(result.postcode,'Unknown') as postcode,
result.state,
result.country,
result.location_category,
result.closed_status_reason,
result.lead_age,
result.total_leads,
result.row_num
FROM result
WHERE row_num = 1
GROUP BY result.date,
result.week,
result.month,
result.leads_id,
result.GA_Id,
result.Name,
result.email,
result.mktg_campaign,
result.mktg_medium,
result.mktg_source,
result.lead_source,
result.category,
result.landing_page,
result.lead_status,
result.business_unit,
result.industry,
result.postcode,
result.state,
result.country,
result.location_category,
result.closed_status_reason,
result.lead_age,
result.total_leads,
result.row_num
ORDER BY date DESC
